#include "run_store.hpp"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QFileInfoList>
#include <QStringList>

#include <chrono>
#include <cstdint>
#include <exception>
#include <utility>

namespace {

/// The inverse of lm::core::to_string(ScriptStatus). Kept here rather than in
/// libs/core -- see the header comment on run_from_json() -- so to_string and
/// this parse live in different files and can drift apart silently. That is
/// exactly why every ScriptStatus (and every TargetState) is round-tripped in
/// tests/test_run_store.cpp: adding a value to either enum becomes a test
/// failure rather than a silently unreadable history file.
std::optional<lm::core::ScriptStatus> script_status_from_string(std::string_view text) {
    if (text == "Completed") return lm::core::ScriptStatus::Completed;
    if (text == "Failed")    return lm::core::ScriptStatus::Failed;
    if (text == "Refused")   return lm::core::ScriptStatus::Refused;
    if (text == "Error")     return lm::core::ScriptStatus::Error;
    return std::nullopt;
}

/// run_id is generated by the server and already filesystem-safe, but
/// save_run() and delete_run() are the last line of defence before it becomes
/// a file name -- a path-traversal guard on a value that happens to be safe
/// today is cheap, and discovering later that it was not is not.
bool is_safe_run_id(const std::string& run_id) {
    return !run_id.empty() && run_id.find('/') == std::string::npos &&
           run_id.find('\\') == std::string::npos && run_id.find("..") == std::string::npos;
}

QString run_file_path(const QString& runs_dir, const std::string& run_id) {
    return QDir(runs_dir).filePath(QString::fromStdString(run_id) + QStringLiteral(".json"));
}

nlohmann::json result_to_json(const lm::transport::ScriptResultMessage& result) {
    return nlohmann::json{
        {"status", lm::core::to_string(result.status)},
        {"refusal_reason", result.refusal_reason},
        {"exit_code", result.exit_code},
        {"has_reported", result.has_reported},
        {"reported_ok", result.reported_ok},
        {"reported_message", result.reported_message},
        {"stdout_text", result.stdout_text},
        {"stderr_text", result.stderr_text},
        {"duration_ms", result.duration_ms},
    };
}

/// Rebuilds the two ScriptResultMessage fields this file does not store on its
/// own: host_id and run_id already live on the enclosing target and run, and
/// storing them a second time inside "result" would be one more place a
/// hand-edited file could disagree with itself.
std::expected<lm::transport::ScriptResultMessage, std::string> result_from_json(
    const nlohmann::json& j, const lm::core::HostId& host_id, const std::string& run_id) {
    lm::transport::ScriptResultMessage result;
    result.host_id = host_id;
    result.run_id = run_id;

    const auto status_text = j.at("status").get<std::string>();
    const auto status = script_status_from_string(status_text);
    if (!status.has_value()) {
        return std::unexpected("unknown script status '" + status_text + "'");
    }
    result.status = *status;
    result.refusal_reason = j.at("refusal_reason").get<std::string>();
    result.exit_code = j.at("exit_code").get<std::int32_t>();
    result.has_reported = j.at("has_reported").get<bool>();
    result.reported_ok = j.at("reported_ok").get<bool>();
    result.reported_message = j.at("reported_message").get<std::string>();
    result.stdout_text = j.at("stdout_text").get<std::string>();
    result.stderr_text = j.at("stderr_text").get<std::string>();
    result.duration_ms = j.at("duration_ms").get<std::uint64_t>();
    return result;
}

nlohmann::json target_to_json(const RunTarget& target) {
    nlohmann::json j{
        {"host_id", target.host_id},
        {"state", to_string(target.state)},
        {"detail", target.detail},
    };
    if (target.result.has_value()) {
        j["result"] = result_to_json(*target.result);
    }
    return j;
}

std::expected<RunTarget, std::string> target_from_json(const nlohmann::json& j,
                                                        const std::string& run_id) {
    RunTarget target;
    target.host_id = j.at("host_id").get<lm::core::HostId>();

    const auto state_text = j.at("state").get<std::string>();
    const auto state = target_state_from_string(state_text);
    if (!state.has_value()) {
        return std::unexpected("unknown target state '" + state_text + "' for host '" +
                                target.host_id + "'");
    }
    target.state = *state;
    target.detail = j.at("detail").get<std::string>();

    if (j.contains("result") && !j.at("result").is_null()) {
        auto result = result_from_json(j.at("result"), target.host_id, run_id);
        if (!result.has_value()) {
            return std::unexpected(result.error());
        }
        target.result = std::move(*result);
    }
    return target;
}

}  // namespace

nlohmann::json run_to_json(const ScriptRun& run) {
    nlohmann::json targets = nlohmann::json::array();
    for (const RunTarget& target : run.targets) {
        targets.push_back(target_to_json(target));
    }

    return nlohmann::json{
        {"run_id", run.run_id},
        {"script_name", run.script_name},
        {"script_body", run.script_body},
        {"issued_at",
         std::chrono::duration_cast<std::chrono::seconds>(run.issued_at.time_since_epoch()).count()},
        {"timeout_seconds", run.timeout_seconds},
        {"targets", targets},
    };
}

std::expected<ScriptRun, std::string> run_from_json(const nlohmann::json& document) {
    // Validated before anything else is touched: without a run_id nothing
    // reloaded could be looked up or deleted, and a document that is not even
    // an object must not be walked field by field looking for one.
    if (!document.is_object() || !document.contains("run_id") || !document.at("run_id").is_string() ||
        document.at("run_id").get<std::string>().empty()) {
        return std::unexpected("missing or empty run_id");
    }
    if (!document.contains("targets") || !document.at("targets").is_array()) {
        return std::unexpected("missing or non-array targets");
    }

    try {
        ScriptRun run;
        run.run_id = document.at("run_id").get<std::string>();
        run.script_name = document.at("script_name").get<std::string>();
        run.script_body = document.at("script_body").get<std::string>();
        run.issued_at = std::chrono::system_clock::time_point(
            std::chrono::seconds(document.at("issued_at").get<std::int64_t>()));
        run.timeout_seconds = document.at("timeout_seconds").get<std::uint32_t>();

        for (const auto& target_json : document.at("targets")) {
            auto target = target_from_json(target_json, run.run_id);
            if (!target.has_value()) {
                return std::unexpected(target.error());
            }
            run.targets.push_back(std::move(*target));
        }
        return run;
    } catch (const std::exception& error) {
        return std::unexpected(error.what());
    }
}

bool save_run(const QString& runs_dir, const ScriptRun& run, QString* error) {
    if (!is_safe_run_id(run.run_id)) {
        if (error != nullptr) {
            *error = QStringLiteral("Refusing to save a run with an unsafe id: %1")
                         .arg(QString::fromStdString(run.run_id));
        }
        return false;
    }

    if (!QDir().mkpath(runs_dir)) {
        if (error != nullptr) {
            *error = QStringLiteral("Could not create runs directory: %1").arg(runs_dir);
        }
        return false;
    }

    QFile file(run_file_path(runs_dir, run.run_id));
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        if (error != nullptr) {
            *error = QStringLiteral("Could not open %1: %2").arg(file.fileName(), file.errorString());
        }
        return false;
    }

    const std::string text = run_to_json(run).dump(2);
    const qint64 written = file.write(text.data(), static_cast<qint64>(text.size()));
    if (written != static_cast<qint64>(text.size())) {
        if (error != nullptr) {
            *error = QStringLiteral("Could not write %1: %2").arg(file.fileName(), file.errorString());
        }
        return false;
    }
    return true;
}

std::vector<ScriptRun> load_runs(const QString& runs_dir, std::vector<QString>* errors) {
    std::vector<ScriptRun> runs;

    const QDir dir(runs_dir);
    if (!dir.exists()) {
        return runs;
    }

    const QFileInfoList entries =
        dir.entryInfoList(QStringList{QStringLiteral("*.json")}, QDir::Files, QDir::Name);
    for (const QFileInfo& entry : entries) {
        QFile file(entry.absoluteFilePath());
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            if (errors != nullptr) {
                errors->push_back(
                    QStringLiteral("Could not open %1: %2").arg(entry.fileName(), file.errorString()));
            }
            continue;
        }
        const QByteArray raw = file.readAll();

        nlohmann::json parsed;
        try {
            parsed = nlohmann::json::parse(raw.constData(), raw.constData() + raw.size());
        } catch (const std::exception& parse_error) {
            if (errors != nullptr) {
                errors->push_back(QStringLiteral("Could not parse %1: %2")
                                       .arg(entry.fileName(), QString::fromUtf8(parse_error.what())));
            }
            continue;
        }

        auto run = run_from_json(parsed);
        if (!run.has_value()) {
            if (errors != nullptr) {
                errors->push_back(QStringLiteral("Could not read %1: %2")
                                       .arg(entry.fileName(), QString::fromStdString(run.error())));
            }
            continue;
        }
        runs.push_back(std::move(*run));
    }
    return runs;
}

bool delete_run(const QString& runs_dir, const std::string& run_id, QString* error) {
    if (!is_safe_run_id(run_id)) {
        if (error != nullptr) {
            *error = QStringLiteral("Refusing to delete a run with an unsafe id: %1")
                         .arg(QString::fromStdString(run_id));
        }
        return false;
    }

    QFile file(run_file_path(runs_dir, run_id));
    if (!file.exists()) {
        if (error != nullptr) {
            *error = QStringLiteral("No such run: %1").arg(QString::fromStdString(run_id));
        }
        return false;
    }
    if (!file.remove()) {
        if (error != nullptr) {
            *error = QStringLiteral("Could not delete %1: %2").arg(file.fileName(), file.errorString());
        }
        return false;
    }
    return true;
}
