find_package(GTest CONFIG REQUIRED)

function(lm_add_test target)
  cmake_parse_arguments(ARG "NO_GTEST_MAIN" "" "SOURCES;LINK" ${ARGN})
  add_executable(${target} ${ARG_SOURCES})
  target_link_libraries(${target} PRIVATE ${ARG_LINK} GTest::gtest GTest::gmock lm_warnings)
  if(NOT ARG_NO_GTEST_MAIN)
    target_link_libraries(${target} PRIVATE GTest::gtest_main)
  endif()
  add_test(NAME ${target} COMMAND ${target})
  set_tests_properties(${target} PROPERTIES FAIL_REGULAR_EXPRESSION "Running 0 tests from 0 test suites")
  copy_runtime_dependencies(${target})
endfunction()
